import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/_Header/header";
import Chat from "./components/_Chat/chat";
import Footer from "./components/_Footer/footer";
import Config from "./components/_Config/config";
import ModalProfile from "./components/_ModalProfile/modalprofile";
import Login from "./(auth)/login/page";
import styles from "./page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PROZZA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>        
      <Login/>
      <div className={styles.container}>
      <Header/>
      <ModalProfile/>
      <div className={styles.main}>
        <Chat/>
        {children}
        <Config/>
      </div>
      <Footer/>
    </div>
      </body>
    </html>
  );
}
